In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
data = pd.read_csv('../data/raw/games.csv')

data.head()

,AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price,DiscountDLC count,About the game,Supported languages,...,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Screenshots,Movies
2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,0,NaN,[],...,0,0,0,NaN,NaN,NaN,NaN,NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,65,0,"Springtime, April: when the cherry trees come ...",['English'],...,0,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,"Adventure,Visual Novel,Anime,Cute",https://shared.akamai.steamstatic.com/store_it...,NaN
1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,0,"Immerse yourself in the most beloved, mystical...","['English', 'French', 'German', 'Russian']",...,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec...",https://shared.akamai.steamstatic.com/store_it...,NaN
3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,0,8.99,0,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",['Korean'],...,0,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
3631080,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,0,4.99,0,0,Its not just a Maze; its a Quest! Enter the ca...,['English'],...,0,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN

In [10]:
data.info()

<class 'pandas.DataFrame'>
Index: 130100 entries, 2539430 to 4441785
Data columns (total 39 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   AppID                       130099 non-null  str
 1   Name                        130100 non-null  str
 2   Release date                130100 non-null  str
 3   Estimated owners            130100 non-null  int64
 4   Peak CCU                    130100 non-null  int64
 5   Required age                130100 non-null  float64
 6   Price                       130100 non-null  int64
 7   DiscountDLC count           130100 non-null  int64
 8   About the game              121343 non-null  str
 9   Supported languages         130100 non-null  str
 10  Full audio languages        130100 non-null  str
 11  Reviews                     12557 non-null   str
 12  Header image                130016 non-null  str
 13  Website                     52164 non-null   str
 14  Support url                 57136 non-null   str
 15  Support email               106696 non-null  str
 16  Windows                     130100 non-null  bool
 17  Mac                         130100 non-null  bool
 18  Linux                       130100 non-null  bool
 19  Metacritic score            130100 non-null  int64
 20  Metacritic url              4382 non-null    str
 21  User score                  130100 non-null  int64
 22  Positive                    130100 non-null  int64
 23  Negative                    130100 non-null  int64
 24  Score rank                  43 non-null      float64
 25  Achievements                130100 non-null  int64
 26  Recommendations             130100 non-null  int64
 27  Notes                       24097 non-null   str
 28  Average playtime forever    130100 non-null  int64
 29  Average playtime two weeks  130100 non-null  int64
 30  Median playtime forever     130100 non-null  int64
 31  Median playtime two weeks   130100 non-null  int64
 32  Developers                  121360 non-null  str
 33  Publishers                  120867 non-null  str
 34  Categories                  120826 non-null  str
 35  Genres                      121390 non-null  str
 36  Tags                        86100 non-null   str
 37  Screenshots                 123865 non-null  str
 38  Movies                      0 non-null       float64
dtypes: bool(3), float64(3), int64(14), str(19)
memory usage: 37.1 MB

In [11]:
data.describe()

,Estimated owners,Peak CCU,Required age,Price,DiscountDLC count,Metacritic score,User score,Positive,Negative,Score rank,Achievements,Recommendations,Average playtime forever,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Movies
count,1.301000e+05,130100.000000,130100.000000,130100.000000,130100.000000,130100.000000,130100.000000,1.301000e+05,1.301000e+05,43.000000,130100.000000,1.301000e+05,1.301000e+05,130100.000000,1.301000e+05,130100.000000,0.0
mean,5.275501e+01,0.166172,4.801549,17.871007,0.532068,2.489654,0.024766,1.021036e+03,1.655089e+02,99.186047,17.841806,9.356119e+02,2.129479e+02,13.525527,1.793116e+02,14.390584,NaN
std,3.624647e+03,1.646404,12.400461,28.616208,14.106005,13.466807,1.398929,2.750974e+04,5.248487e+03,0.663892,137.874624,2.136105e+04,1.188289e+04,268.939807,1.186861e+04,291.788384,NaN
min,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,98.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,NaN
25%,0.000000e+00,0.000000,0.590000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,99.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,NaN
50%,0.000000e+00,0.000000,2.390000,0.000000,0.000000,0.000000,0.000000,4.000000e+00,1.000000e+00,99.000000,2.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,NaN
75%,0.000000e+00,0.000000,5.490000,35.000000,0.000000,0.000000,0.000000,3.400000e+01,1.000000e+01,100.000000,19.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,NaN
max,1.013936e+06,21.000000,999.980000,100.000000,3703.000000,97.000000,100.000000,7.642084e+06,1.173003e+06,100.000000,9821.000000,4.830455e+06,3.429544e+06,20088.000000,3.429544e+06,20088.000000,NaN